- name: Check if Docker is installed
  command: docker --version
  register: docker_check

- name: Print message
  debug:
    msg: "Docker is already present {{ docker_check }}"
  when: docker_check.rc == 0

- name: Install Docker
  become: yes
  apt:
    name: docker.io
    state: present
  when: docker_check.rc != 0

- name: Install Docker Compose
  become: yes
  apt:
    name: docker-compose
    state: present

- name: Check if user exist in docker group
  ansible.builtin.shell: |
    grep -q /etc/group -e "docker" 
  register: result

- name: Adding user to docker group
  become: yes
  shell: |
    gpasswd -a $USER docker
    newgrp docker
  when: result.rc != 0

- name: Make sure docker is started
  become: yes
  service:
    name: docker
    state: started

- name: Check if Fossology image is present
  command: docker images fossology/fossology
  register: fossology_image_check
  failed_when: fossology_image_check.rc != 0

- name: Pulling fossology image
  become: yes
  community.docker.docker_image:
    name: fossology/fossology
    source: pull
    state: present
  when: fossology_image_check.rc != 0



