---
- name: Pulling down docker image from fossology/fossology
  ansible.builtin.include_tasks: install_from_docker.yml
  when: fosslogy_install_from_docker == true

- name: Installing fossology from source
  ansible.builtin.include_tasks: install_from_source.yml
  when: fossology_install_from_source == true