---
- name: Adding user to docker group
  become: yes
  shell: |
    gpasswd -a $USER docker
    newgrp docker

- name: Make sure docker is started
  service:
    name: docker
    state: started

- name: Pulling fossology image
  become: yes
  community.docker.docker_image:
    name: fossology/fossology
    source: pull
    state: present



